### PR TITLE
Fix `devDefault: undefined` typings

### LINKED ISSUE #201: str({ devDefault: undefined }) generates an incorrect type
`str({ devDefault: undefined })` is intended to return undefined in development, based on this existing test:

https://github.com/af/envalid/blob/53f54e94108b7d1eaadba59c9883b0b6f4318e54/tests/basics.test.ts#L53-L59

However, the type of the resulting value is reported as `string` instead of `string | undefined`.

### PR DESCRIPTION
**Pull request by jsamr**
Fixes

- #201 

Basically, setting `devDefault: undefined` should behave exactly as `default: undefined` type-wise. The output value should be unionized with `undefined`. This PR also introduces stricter typings tests by using `toEqualTypeOf` instead of `toMatchTypeOf`, the latter being more lax when it comes to undefined values.

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -26,31 +26,28 @@ export interface Spec<T> {
   devDefault?: NonNullable<T> | undefined
 }
 
-type OptionalSpec<T> = Omit<Spec<T>, 'default'> & { default: undefined }
+type OptionalFlag<T> =
```
Comment (af) [inline src/types.ts:29]: `Flag` is a little confusing to me here. Would it make sense to change the suffix to `Attrs`, both here and for `RequiredFlag`?

File: tests/types.test.ts [hunk 2]
```diff
@@ -243,36 +252,42 @@ test('cleanEnv', () => {
...
-    readonly BOOL_DEFAULT: boolean
-    readonly NUM: number
-    readonly NUM_DEFAULT_CHOICES: 1 | 2 | 3
-    readonly JSON_ANY: any
-    readonly JSON_REQ_ANY: any
-    readonly JSON_DEFAULT: { foo: string }
-    readonly JSON_DEV_DEFAULT: { foo: string }
-    readonly JSON_DEFAULT_OPT?: { foo: string }
-  }
+  type TestedCleanedEnv = Readonly<
```
Comment (af) [inline tests/types.test.ts:255]: Nice, this change reads a lot better 👍

**Review by af — COMMENTED** [review]
One naming suggestion, otherwise looks good. Thanks for jumping on this, appreciate it!

**Comment by jsamr** [comment]
@af ✅ 

**PS**: we were thinking internally that it would make sense to have a `testDefault` for unit-tests instead of `testOnly` helper, to have a uniform API. What do you think?

**Comment by af** [comment]
Thanks!

re: `testDefault`, I think this was suggested a while back, I'll have to find the rationale for why it's the way it is (would have been several years ago). I don't think `testOnly` is that widely used so maybe soft-deprecating it and doing that is worth considering 🤔
